### PR TITLE
macOS support

### PR DESCRIPTION
**Pull request by Meorge**
I've gotten this library to work with the included demo project on macOS Catalina 10.15.4. The necessary steps to get it running have been added to the README. I did not include the dylib files in the demo project, since I'm a bit unsure if sharing them is allowed, but they can be downloaded from FMOD's website.

### CODE REVIEW

**Comment by Meorge** [comment]
Some unfortunate news - while the included demo project still runs fine on macOS, I started trying to get it running with a MonoGame project of mine, and I'm receiving the following error:

```
Unable to load shared library 'fmodstudio.dll' or one of its dependencies.
In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:
dlopen(libfmodstudio.dll, 1): image not found
```

To "install" the library in my project, I built it in Debug mode, then imported the file `ChaiFoxes.FMODAudio/bin/Release/ChaiFoxes.FMODAudio.Desktop/ChaiFoxes.FMODAudio.Desktop.dll` into my project as an assembly. My guess here is that it's not including the `ChaiFoxes.FMODAudio.Desktop.dll.config` file, and thus not receiving the `dllmap` statements. 

It is also worth noting that my project is apparently using .NET Core 3.0, while this library is built with .NET Framework 4.5 - I will look into seeing if a project created with Framework 4.5 works better.

**Comment by SenpaiSharp** [comment]
> I will look into seeing if a project created with Framework 4.5 works better.

Any word on how this went?

**Comment by Meorge** [comment]
> > I will look into seeing if a project created with Framework 4.5 works better.
> 
> Any word on how this went?

Unfortunately it's been such a long time since I was last working on this that I forgot a lot of what specifically I did to get it working. However, I do have a MonoGame project running with .NET Core 3.1 on macOS that works! You can find it at https://github.com/Meorge/ChaiFoxes.FMODAudio. (You'll need to download the .dylibs directly from FMOD though.)

**Comment by Martenfur** [comment]
Too outdated.

**Pull request closed without merging**
